//! Differential ("golden") test of the Rust port against Python RotorPy.
//!
//! Fixtures live in `../fixtures/sim/*.json` (generated by
//! `scripts/export_fixtures.py`). Two gates per fixture:
//!   1. derivative gate  — Rust `state_derivative` vs RotorPy's 20-dim `s_dot`
//!      at each pre-step state (integrator-independent; pins transcription bugs).
//!   2. step/rollout gate — per-step (reset to truth each step) and free-running
//!      rollout, vs RotorPy's integrated states.

use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use rotor_rs::{Ctbr, CtbrCmd, Multirotor, QuadParamsInput, RotorForce, State, Vec3};
use rotor_rs::{Quat, STATE_LEN};

// Fixed substeps per control step for the fixed-step RK4 integrator. 8 keeps the
// stiff fast-motor case (tau_m ~ dt) well inside tolerance; still trivially cheap.
const N_SUB: usize = 8;

// ---- tolerances ----------------------------------------------------------- //
// All gates use a normalized error: max_i |rust_i - py_i| / (atol + rtol*|py_i|),
// so each component is judged on its own scale (position ~1 m vs rotor speed
// ~1000 rad/s). Pass when <= 1.
//
// Derivative gate: tight (only float-reordering vs numpy should differ).
const SDOT_RTOL: f64 = 1e-6;
const SDOT_ATOL: f64 = 1e-6;
// Step gate: fixed RK4 vs scipy adaptive RK45 over one 5 ms step.
const STEP_RTOL: f64 = 1e-4;
const STEP_ATOL: f64 = 1e-3;
// Rollout gate: accumulated over the whole trajectory (looser).
const ROLLOUT_RTOL: f64 = 1e-3;
const ROLLOUT_ATOL: f64 = 1e-2;

// --------------------------------------------------------------------------- //
// Fixture JSON schema
// --------------------------------------------------------------------------- //
#[derive(Deserialize)]
struct Fixture {
    name: String,
    abstraction: String,
    dt: f64,
    params: PJson,
    initial_state: SJson,
    steps: Vec<StepJson>,
}

#[derive(Deserialize)]
struct StepJson {
    cmd: serde_json::Value,
    sdot: Vec<f64>,
    state: SJson,
}

#[derive(Deserialize)]
#[allow(non_snake_case)]
struct PJson {
    mass: f64,
    Ixx: f64,
    Iyy: f64,
    Izz: f64,
    Ixy: f64,
    Iyz: f64,
    Ixz: f64,
    rotor_pos: Vec<[f64; 3]>,
    rotor_directions: Vec<f64>,
    c_Dx: f64,
    c_Dy: f64,
    c_Dz: f64,
    k_eta: f64,
    k_m: f64,
    k_d: f64,
    k_z: f64,
    k_h: f64,
    k_flap: f64,
    tau_m: f64,
    rotor_speed_min: f64,
    rotor_speed_max: f64,
    k_w: f64,
}

#[derive(Deserialize)]
struct SJson {
    x: [f64; 3],
    v: [f64; 3],
    q: [f64; 4],
    w: [f64; 3],
    wind: [f64; 3],
    rotor_speeds: [f64; 4],
}

// --------------------------------------------------------------------------- //
// Conversions
// --------------------------------------------------------------------------- //
impl PJson {
    fn to_input(&self) -> QuadParamsInput {
        let mut rotor_pos = [[0.0; 3]; 4];
        let mut rotor_directions = [0.0; 4];
        for r in 0..4 {
            rotor_pos[r] = self.rotor_pos[r];
            rotor_directions[r] = self.rotor_directions[r];
        }
        QuadParamsInput {
            mass: self.mass,
            ixx: self.Ixx,
            iyy: self.Iyy,
            izz: self.Izz,
            ixy: self.Ixy,
            iyz: self.Iyz,
            ixz: self.Ixz,
            rotor_pos,
            rotor_directions,
            c_dx: self.c_Dx,
            c_dy: self.c_Dy,
            c_dz: self.c_Dz,
            k_eta: self.k_eta,
            k_m: self.k_m,
            k_d: self.k_d,
            k_z: self.k_z,
            k_h: self.k_h,
            k_flap: self.k_flap,
            tau_m: self.tau_m,
            rotor_speed_min: self.rotor_speed_min,
            rotor_speed_max: self.rotor_speed_max,
            k_w: self.k_w,
        }
    }
}

impl SJson {
    fn to_state(&self) -> State<f64> {
        State {
            x: Vec3::new(self.x[0], self.x[1], self.x[2]),
            v: Vec3::new(self.v[0], self.v[1], self.v[2]),
            q: Quat::new(self.q[0], self.q[1], self.q[2], self.q[3]),
            w: Vec3::new(self.w[0], self.w[1], self.w[2]),
            wind: Vec3::new(self.wind[0], self.wind[1], self.wind[2]),
            rotor_speeds: self.rotor_speeds,
        }
    }
}

fn rotor_force_cmd(v: &serde_json::Value) -> [f64; 4] {
    let a = v["cmd_motor_thrusts"].as_array().unwrap();
    [
        a[0].as_f64().unwrap(),
        a[1].as_f64().unwrap(),
        a[2].as_f64().unwrap(),
        a[3].as_f64().unwrap(),
    ]
}

fn ctbr_cmd(v: &serde_json::Value) -> CtbrCmd<f64> {
    let w = v["cmd_w"].as_array().unwrap();
    CtbrCmd {
        thrust: v["cmd_thrust"].as_f64().unwrap(),
        w_cmd: Vec3::new(
            w[0].as_f64().unwrap(),
            w[1].as_f64().unwrap(),
            w[2].as_f64().unwrap(),
        ),
    }
}

// ---- comparison helpers --------------------------------------------------- //
fn sdot_err(rust: &[f64; STATE_LEN], py: &[f64]) -> f64 {
    let mut worst = 0.0_f64;
    for i in 0..STATE_LEN {
        let d = (rust[i] - py[i]).abs();
        let tol = SDOT_ATOL + SDOT_RTOL * py[i].abs();
        worst = worst.max(d / tol); // normalized error; >1 means fail
    }
    worst
}

/// Normalized per-component state error (max_i |d_i|/(atol+rtol*|py_i|)), with
/// sign-insensitive quaternion compare. <= 1 means within tolerance.
fn state_err(a: &State<f64>, b: &SJson, atol: f64, rtol: f64) -> f64 {
    let mut e = 0.0_f64;
    let norm = |x: f64, y: f64| (x - y).abs() / (atol + rtol * y.abs());
    let pairs = [
        (a.x.x, b.x[0]), (a.x.y, b.x[1]), (a.x.z, b.x[2]),
        (a.v.x, b.v[0]), (a.v.y, b.v[1]), (a.v.z, b.v[2]),
        (a.w.x, b.w[0]), (a.w.y, b.w[1]), (a.w.z, b.w[2]),
        (a.rotor_speeds[0], b.rotor_speeds[0]),
        (a.rotor_speeds[1], b.rotor_speeds[1]),
        (a.rotor_speeds[2], b.rotor_speeds[2]),
        (a.rotor_speeds[3], b.rotor_speeds[3]),
    ];
    for (x, y) in pairs {
        e = e.max(norm(x, y));
    }
    // quaternion: q and -q are equal rotations
    let aq = a.q.to_array();
    let mut d_pos = 0.0_f64;
    let mut d_neg = 0.0_f64;
    for k in 0..4 {
        d_pos = d_pos.max(norm(aq[k], b.q[k]));
        d_neg = d_neg.max((aq[k] + b.q[k]).abs() / (atol + rtol * b.q[k].abs()));
    }
    e.max(d_pos.min(d_neg))
}

// --------------------------------------------------------------------------- //
// Test driver
// --------------------------------------------------------------------------- //
fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../fixtures/sim")
}

fn load_fixtures() -> Vec<(String, Fixture)> {
    let dir = fixture_dir();
    let mut out = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {dir:?}: {e} (run scripts/export_fixtures.py)"))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "json").unwrap_or(false))
        .collect();
    entries.sort();
    for path in entries {
        let txt = fs::read_to_string(&path).unwrap();
        let fx: Fixture = serde_json::from_str(&txt).unwrap();
        out.push((path.file_name().unwrap().to_string_lossy().into(), fx));
    }
    assert!(!out.is_empty(), "no fixtures found in {:?}", dir);
    out
}

/// Run all three gates for one abstraction. `mk_cmd` extracts the typed command
/// from the JSON cmd value.
fn run_fixture<C, F>(fx: &Fixture, mk_cmd: F) -> (f64, f64, f64)
where
    C: rotor_rs::ControlLaw<f64>,
    F: Fn(&serde_json::Value) -> C::Command,
{
    let input = fx.params.to_input();
    let veh: Multirotor<f64, C> = Multirotor::with_substeps(&input, N_SUB);

    let mut worst_sdot = 0.0_f64;
    let mut worst_step = 0.0_f64;

    // pre-state for step t: initial_state for t==0, else previous truth state.
    let mut rollout = fx.initial_state.to_state();
    let mut worst_rollout = 0.0_f64;

    for (t, step) in fx.steps.iter().enumerate() {
        let cmd = mk_cmd(&step.cmd);
        let pre = if t == 0 {
            fx.initial_state.to_state()
        } else {
            fx.steps[t - 1].state.to_state()
        };

        // gate 1: derivative
        let dsd = veh.state_derivative(&pre, &cmd);
        worst_sdot = worst_sdot.max(sdot_err(&dsd, &step.sdot));

        // gate 2a: per-step (reset to truth each step)
        let stepped = veh.step(&pre, &cmd, fx.dt);
        worst_step = worst_step.max(state_err(&stepped, &step.state, STEP_ATOL, STEP_RTOL));

        // gate 2b: free-running rollout
        rollout = veh.step(&rollout, &cmd, fx.dt);
        worst_rollout =
            worst_rollout.max(state_err(&rollout, &step.state, ROLLOUT_ATOL, ROLLOUT_RTOL));
    }
    (worst_sdot, worst_step, worst_rollout)
}

#[test]
#[ignore = "diagnostic: dumps per-component derivative diff for one step"]
fn debug_first_step() {
    let fixtures = load_fixtures();
    let (_, fx) = fixtures
        .iter()
        .find(|(n, _)| n.starts_with("nominal_cmd_motor_thrusts"))
        .unwrap();
    let input = fx.params.to_input();
    let veh: Multirotor<f64, RotorForce> = Multirotor::with_substeps(&input, N_SUB);
    let pre = fx.initial_state.to_state();
    let step = &fx.steps[0];
    let cmd = rotor_force_cmd(&step.cmd);
    let speeds = veh.clipped_cmd_speeds(&pre, &cmd);
    println!("cmd forces = {:?}", cmd);
    println!("clipped cmd speeds = {:?}", speeds);
    println!("pre rotor_speeds = {:?}", pre.rotor_speeds);
    let dsd = veh.state_derivative(&pre, &cmd);
    let names = [
        "xd0", "xd1", "xd2", "vd0", "vd1", "vd2", "qd0", "qd1", "qd2", "qd3", "wd0",
        "wd1", "wd2", "windd0", "windd1", "windd2", "ra0", "ra1", "ra2", "ra3",
    ];
    for i in 0..STATE_LEN {
        let d = (dsd[i] - step.sdot[i]).abs();
        println!(
            "{:7} rust={:+.6e}  py={:+.6e}  |d|={:.3e}",
            names[i], dsd[i], step.sdot[i], d
        );
    }
}

#[test]
fn golden_all_fixtures() {
    let fixtures = load_fixtures();
    let mut failures = Vec::new();

    for (name, fx) in &fixtures {
        let (sdot_n, step_e, roll_e) = match fx.abstraction.as_str() {
            "cmd_motor_thrusts" => run_fixture::<RotorForce, _>(fx, rotor_force_cmd),
            "cmd_ctbr" => run_fixture::<Ctbr, _>(fx, ctbr_cmd),
            other => panic!("unknown abstraction {other} in {name}"),
        };
        // all three are normalized errors (fail if > 1).
        let ok = sdot_n <= 1.0 && step_e <= 1.0 && roll_e <= 1.0;
        println!(
            "{:30} sdot={:.3e}  step={:.3e}  rollout={:.3e}  {}",
            fx.name,
            sdot_n,
            step_e,
            roll_e,
            if ok { "OK" } else { "FAIL" }
        );
        if !ok {
            failures.push(format!(
                "{}: sdot={:.3e} step={:.3e} rollout={:.3e}",
                name, sdot_n, step_e, roll_e
            ));
        }
    }

    assert!(failures.is_empty(), "golden mismatches:\n{}", failures.join("\n"));
}
